### PR TITLE
Redux in React

### PR DESCRIPTION
**Pull request by riskmaris**
For this milestone I;

- [ ] Wrapped my <App> with the <Provider> component from react-redux.
- [ ] Passed my configured store into the <Provider>.
- [ ] Created an initialState variable for my booksSlice.
- [ ] Dispatched actions using useDispatch.
- [ ] Added a <Button> component, which includes:
1. An event handler that adds a book to the books array.
- [ ] Added a <Button> component, which includes:
1. An event handler that removes a book from the books array (by id)

### CODE REVIEW

**Review by levy002 — CHANGES_REQUESTED** [review]
## Hello @riskmaris   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights 
- No linter error :heavy_check_mark: 

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

- [ ] Certainly! When aiming to display a collection of books fetched from the Redux store, I recommend utilizing the `useSelector` hook provided by `react-redux`. By employing this approach, you can selectively extract the book data from the store's state and render only those books on your page. This ensures that your UI remains aligned with the data present in your Redux store, promoting consistency and a single source of truth. Keep up the great work! 📚👩‍💻

   _**You need to refactor your code in `src/components/books/books.jsx**_

- [ ] Certainly! When it comes to removing a book from your Redux store, consider utilizing the `useDispatch` hook provided by `react-redux`. This hook enables you to dispatch actions to update the store, including removing items. By dispatching a well-defined action to remove a book, you maintain a clear and controlled flow of data modifications within your application. This approach enhances predictability and adherence to Redux principles. Keep up the excellent work, and feel free to explore the powerful combination of `useSelector` and `useDispatch` for a robust Redux implementation! 📖🚀

  _**You need to refactor your code in `src/components/books/homepage.js**_

- [ ] Absolutely! When adding a new book to your Redux store, I recommend leveraging the combined power of `useSelector` and `useDispatch` from `react-redux`, alongside appropriate event handlers like `onClick` or `onChange`.

Here's a high-level approach:

1. **useSelector**: Utilize this hook to access the necessary parts of your Redux store, such as the book data or any relevant state.

2. **useDispatch**: Employ this hook to dispatch an action that adds the new book to the store. You can define the action and its payload in your Redux setup.

3. **Event Handling**: Attach the event handlers, like `onClick` or `onChange`, to the appropriate UI elements in your component. For instance, you might use `onClick` on a "Add Book" button or `onChange` on input fields.

_**You need to refactor your code in `src/components/form/form.jsx**_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by ghost — CHANGES_REQUESTED** [review]
Hi @riskmaris , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!




## Highlights

✅ Correct use of Gitflow
✅ No linter error
✅ Good work making some of the changes requested 👍 



## Required Changes ♻️
- [ ]  Your Bookstore project is shaping up well! Noticed the form submit button doesn't add books. 📚  Kindly add a function that dispatches the `addBook` action and prevents the form's default submission. Excited to see it in action! Keep coding! 💻🚀

## Optional suggestions
N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by brainconnect93 — CHANGES_REQUESTED** [review]
### Hi @riskmaris, 👋 

# STATUS: Changes Required :recycle:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



# Good Points 👍

- Descriptive Pull Request title & summary. ✔️
- `initialState` has been added to the `booksSlice` ✔️
- Has `<Provider>` component from `react-redux` ✔️
- Has `<BookList>` with `useSelector` ✔️
- Has a Component for Adding and Removing Books ✔️
- Good use of GitFlow ✔️

### Changes Required

- [x] Hello @riskmaris  great effort working on your project, but i realized you haven't still work on the changes requested by the previous reviewer and i would kindly suggest you check all the review both inline and general comment to be sure you didn't leave any suggestion behind unattended to.
Below is a video demonstration talking about your page behavior and what you need to work on.

[screen-capture (2).webm](https://github.com/riskmaris/bookstore/assets/78634841/eaf67d1d-0dde-4bbf-bc3d-9649f143fa36)


- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by riskmaris** [comment]
Hi @brainconnect93 
Surprisingly on side it works perfectly well

**Review by BenMukebo — APPROVED** [review]
### Hi @riskmaris, 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 



### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- I can add a new book and remove from the list. 🥇  


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
